openapi: 3.0.0
info:
  title: Bowling Game API
  version: 1.0.0
paths:
  /api/game:
    post:
      summary: Create a new game
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateGameRequest'
      responses:
        201:
          description: Game created successfully
          content:
            application/json:
              schema:
                type: integer
                format: int64
        default:
          $ref: '#/components/responses/ApiErrorResponse'
    put:
      summary: Update an existing game
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BowlingGameInfo'
      responses:
        200:
          description: Game updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BowlingGameInfo'
        default:
          $ref: '#/components/responses/ApiErrorResponse'

  /api/game/roll:
    put:
      summary: Perform a roll in a game
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RollRequest'
      responses:
        200:
          description: Roll performed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BowlingGameInfo'
        default:
          $ref: '#/components/responses/ApiErrorResponse'

  /api/game/{id}:
    get:
      summary: Retrieve a game by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Game found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BowlingGameInfo'
        default:
          $ref: '#/components/responses/ApiErrorResponse'
    delete:
      summary: Delete a game by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Game deleted successfully
        default:
          $ref: '#/components/responses/ApiErrorResponse'

  /api/game/{id}/score:
    get:
      summary: Retrieve the score for a game by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Game score retrieved successfully
          content:
            application/json:
              schema:
                type: integer
                format: int32
        default:
          $ref: '#/components/responses/ApiErrorResponse'

components:
  schemas:
    CreateGameRequest:
      type: object
      properties:
        uid:
          type: string
        game:
          $ref: '#/components/schemas/BowlingGameInfo'
    BowlingGameInfo:
      type: object
      properties:
        id:
          type: integer
          format: int64
        frames:
          type: array
          items:
            $ref: '#/components/schemas/FrameInfo'
        player:
          type: string
        lane:
          type:string
        gameSet:
          type: integer
          format: int64

        FrameInfo:
          type: object
          properties:
            rolls:
              type: array
              items:
                $ref: '#/components/schemas/RollInfo'
        RollInfo:
          type: object
          properties:
            pins:
              type: integer
              format: int32
            marker:
              type: string
              nullable: true
            uid:
              type: string
              nullable: true

        RollRequest:
          type: object
          properties:
            gameId:
              type: integer
              format: int64
            roll:
              $ref: '#/components/schemas/RollInfo'
            uid:
              type: string
              nullable: true

        responses:
          ApiErrorResponse:
            description: Generic error response
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ApiLayerError'

        schemas:
          ApiLayerError:
            type: object
            properties:
              error:
                type: string
              ref:
                type: string
                nullable: true

