version: '3.8'
services:
  postgres:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=game
    logging:
      options:
        max-size: 10m
        max-file: "3"
    network_mode: host
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./scripts/create_bowling_database.sql:/docker-entrypoint-initdb.d/create_bowling_database.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 20s
      retries: 2

  bowling:
    image: fahsi/bowling-api:1.0-SNAPSHOT
    environment:
      - STORAGE_DB=postgres
    command: java -Dstorage.db=${STORAGE_DB:-postgres} -jar /opt/docker/bin/bowling
    network_mode: host
    depends_on:
      postgres:
        condition: service_started


